AllCops:
  Exclude:
    - "spec/spec_helper.rb"
  NewCops: enable
Metrics:
  Exclude:
    - "lib/board.rb"
    - "lib/utility/*"
    - "spec/**/*"
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
Layout/LineLength:
  Exclude:
    - "spec/**/*"
Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"